version: "3.2"

services:
  smartcontract:
    build:
      context: .
    container_name: "smartcontract"
    volumes:
      - type: bind
        source: ./
        target: /home/node/app/
      - /home/node/app/node_modules
    ports:
      - "8089:8000"
    networks:
      - net
    entrypoint: sh
    command: '-c "sleep 1d"'
    links:
      - eth-node
      - bsc-node
    env_file:
      - ./.env
    cap_add:
      - IPC_LOCK
  eth-node:
    build:
      context: ./ganache
    container_name: "eth-node"
    ports:
      - 8545:8545
    networks:
      - net
    env_file:
      - ./.env
    volumes:
      - type: bind
        source: ./ganache/ganache_with_accounts.sh
        target: /app/ganache_with_accounts.sh
    command: "bash ganache_with_accounts.sh"
  bsc-node:
    build:
      context: ./ganache
    container_name: "bsc-node"
    ports:
      - 8546:8545
    networks:
      - net
    env_file:
      - ./.env
    volumes:
      - type: bind
        source: ./ganache/ganache_with_accounts.sh
        target: /app/ganache_with_accounts.sh
    command: "bash ganache_with_accounts.sh"
networks:
  net:
